# typed: true
require 'parlour'

class HelperRbiFormatter
  # @param [Array<String>] helpers
  # @return [void]
  def initialize(helpers)
    @parlour = Parlour::RbiGenerator.new
    @helpers = helpers
  end

  # Generates RBI file's contents.
  # @return [String]
  def generate_rbi
    puts "-- Generate sigs for helpers --"

    @parlour.root.add_comments([
      'This is an autogenerated file for Rails helpers.',
      'Please rerun rake rails_rbi:helpers to regenerate.'
    ])

    @helpers.each do |helper|
      @parlour.root.create_module(name: helper) do |mod|
        mod.create_include(name: 'Kernel')
      end
    end

    return @parlour.rbi
  end
end
